@startuml overview
scale 700 width

skinparam agent {
    BackgroundColor White
    BorderColor Black
}
skinparam database {
    BackgroundColor White
    BorderColor Black
}

rectangle "Real System" as r {
    agent "\nDeliberation Layer\n" as rdelib #LightYellow
    agent "\nSkill Layer\n" as rskill #LightYellow
    agent "\nFunctional Layer\n" as rfunc #LightYellow
    agent "\nReal Environment\n" as renv #LightYellow

    rdelib --> rskill
    rskill --> rfunc
    rfunc --> renv
}

file "Model" as m {
    agent "\nDeliberation Layer Model\n" as mdelib #LightBlue
    agent "\nSkill Layer Model\n" as mskill #LightBlue
    agent "\nFunctional Layer Model\n" as mfunc #LightBlue
    agent "\nEnvironment Model\n" as menv #LightBlue

    mdelib --> mskill
    mskill --> mfunc
    mfunc --> menv
}

database "Knowledge Model\n" as k 

' WP2

agent sitaw #LightGreen [
[[https://convince-project.github.io/overview/#sit-aw SIT-AW]]
....
WP2 / CEA

----
[[https://convince-project.github.io/overview/#sit-l SIT-L]]
....
WP2 / CEA
]
' }

renv -[hidden]> sitaw
rskill .. sitaw
sitaw <-> k : OWL


' WP3

agent refineplan #PaleGreen [
[[https://convince-project.github.io/overview/#refine-plan REFINE-PLAN]]
....
WP3 / UoB
] 
agent coverageplan #PaleGreen [
[[https://convince-project.github.io/overview/#coverage-plan COVERAGE-PLAN]]
....
WP3 / UoB
]
agent activeplan #PaleGreen [
[[https://convince-project.github.io/overview/#active-plan-simulate-plan ACTIVE-PLAN]]
....
WP3 / UoB
] 
agent simulateplan #PaleGreen [
[[https://convince-project.github.io/overview/#active-plan-simulate-plan SIMULATE-PLAN]]
....
WP3 / UoB
] 

rskill .. coverageplan
rfunc -[hidden]> coverageplan
activeplan <-> simulateplan : root-cause
mdelib -> refineplan : "\nBT.cpp XML"
refineplan -> rdelib : "BT.cpp XML"
rdelib -> simulateplan : "BT.cpp XML"
k -> simulateplan : "\nOWL"
k -> activeplan : OWL

' WP4

agent moon #TECHNOLOGY [
[[https://convince-project.github.io/overview/#moon MOON]]
....
WP4 / UniGe
]
' ]
agent stormscan #TECHNOLOGY [
[[https://convince-project.github.io/overview/#smc-storm SMC-STORM]]
....
WP4 / Bosch

----
[[https://convince-project.github.io/overview/#scan SCAN]]
....
WP4 / UniGe
]
agent jani #TECHNOLOGY [
[[https://convince-project.github.io/overview/#mc-toolchain-jani MC-TOOLCHAIN-JANI]]
....
WP4 / Bosch
]
agent modeltocode #TECHNOLOGY [
[[https://convince-project.github.io/overview/#model2code MODEL2CODE]]
....
WP4 / IIT
]

moon -[hidden]-> rdelib
moon <-- r : ROS Communication

stormscan -[hidden]-> mdelib
stormscan <-- m : "JANI / SCXML\n"

r -> jani : "SCXML"
jani -> m : "JANI\n"
rskill <- modeltocode : "CPP"
modeltocode <- mskill : "SCXML\t\t\t"
coverageplan -[hidden]> modeltocode

refineplan -[hidden]-> modeltocode


rectangle Legend as legend {
    agent a [
    ]
    agent b [
    ]
    a -> b : "data flow"

    agent c [
    ]
    agent d [
    ]
    c . d : "contained in"
}

renv -[hidden]-> legend

@enduml
