@startuml overview
scale 700 width

skinparam agent {
    BackgroundColor White
    BorderColor Black
}
skinparam database {
    BackgroundColor White
    BorderColor Black
}

rectangle "Real System" as r {
    agent "\nDeliberation Layer\n" as rdelib #LightYellow
    agent "\nSkill Layer\n" as rskill #LightYellow
    agent "\nFunctional Layer\n" as rfunc #LightYellow
    agent "\nReal Environment\n" as renv #LightYellow

    rdelib --> rskill
    rskill --> rfunc
    rfunc --> renv
}

file "Model" as m {
    agent "\nDeliberation Layer Model\n" as mdelib #LightBlue
    agent "\nSkill Layer Model\n" as mskill #LightBlue
    agent "\nFunctional Layer Model\n" as mfunc #LightBlue
    agent "\nEnvironment Model\n" as menv #LightBlue

    mdelib --> mskill
    mskill --> mfunc
    mfunc --> menv
}

m -[hidden]> r

renv -[hidden]> menv
rdelib -[hidden]> mdelib

database "Knowledge Model\n" as k 

' renv -[hidden]> k
' k -[hidden]> menv

' WP2

' rectangle WP2 #line.dashed{
agent sitaw #LightGreen [
[[https:///github.com/convince-project/sit-aw SIT-AW]]
....
WP2 / CEA
]
' }

sitaw -[hidden]> rskill
rskill .. sitaw
sitaw <-> k : OWL

' WP3

' rectangle WP3 #line.dashed {
agent refineplan #PaleGreen [
[[https://github.com/convince-project/refine-plan REFINE-PLAN]]
....
WP3 / UoB
] 
agent coverageplan #PaleGreen [
[[https:///github.com/convince-project/coverage-plan COVERAGE-PLAN]]
....
WP3 / UoB
]
agent activeplan #PaleGreen [
[[https://github.com/convince-project/active-plan ACTIVE-PLAN]]
....
WP3 / UoB
] 
agent simulateplan #PaleGreen [
[[https://github.com/convince-project/simulate-plan SIMULATE-PLAN]]
....
WP3 / UoB
] 
refineplan -[hidden]-> simulateplan
simulateplan -[hidden]-> activeplan
' }

coverageplan .. rskill
activeplan <-> simulateplan : root-cause
mdelib -> refineplan : "BT.cpp XML"
refineplan -> rdelib : "BT.cpp XML"
rdelib -> simulateplan : "BT.cpp XML"
k -> simulateplan : OWL
k -> activeplan : OWL

' WP4

' rectangle WP4 #line.dashed {
agent moon #TECHNOLOGY [
[[https:///github.com/convince-project/moon MOON]]
....
WP4 / UniGe
]
' together {
' agent scan #TECHNOLOGY [
' [[https:///github.com/convince-project/scan SCAN]]
' ....
' WP4 / UniGe
' ]
agent storm #TECHNOLOGY [
[[https:///github.com/convince-project/smc_storm SMC-STORM]]
....
WP4 / Bosch

----
[[https:///github.com/convince-project/scan SCAN]]
....
WP4 / UniGe
]
' scan -[hidden]-> storm
' }
' together {
agent jani #TECHNOLOGY [
[[https:///github.com/convince-project/mc-toolchain-jani MC-TOOLCHAIN-JANI]]
....
WP4 / Bosch
]
agent modeltocode #TECHNOLOGY [
[[https:///github.com/convince-project/modeltocode MODEL2CODE]]
....
WP4 / IIT
]
' }
' activeplan -[hidden]-> jani
activeplan -[hidden]-> modeltocode

' moon -[hidden]> scan
moon -[hidden]-> rdelib

moon <-- r : ROS Communication

m -> storm : "JANI / SCXML"
' m -> storm : "SCXML"

r -> jani : "SCXML"
jani -> m : "JANI"
rskill <- modeltocode : "CPP"
modeltocode <- mskill : "SCXML"

refineplan -[hidden]> jani
@enduml
