connection.tls_enabled=true
connection.use_cloud_address_translation=false
connection.server=TypeDB Core
connection.core_address=localhost\:1729
connection.advanced_config_selected=true
project.path=/convince_ws/src/tutorials/semantic_reasoning_demo/misc/anchoring/tql
connection.cloud_addresses=
connection.ca_certificate=
connection.username=
connection.cloud_address_translation=
