<?xml version="1.0"?>
<package format="3">
	<name>semantic_reasoning_bringup</name>
	<version>0.1.0</version>
  <description>Bringup launcher for the semantic reasoning demo in Convince Overarching Tutorial</description>
  <author email="matteo.morelli@cea.fr">Matteo MORELLI</author>
  <maintainer email="matteo.morelli@cea.fr">Matteo MORELLI</maintainer>
  <license>CeCILL-B</license>

	<buildtool_depend>ament_cmake</buildtool_depend>

	<depend>rclcpp</depend>
	<depend>rclcpp_lifecycle</depend>
<!--	<depend>anchoring_process</depend>-->
  <depend>tutorial_skill_executor </depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>
</package>
